'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
Namespace My


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property arrowleft_green_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("arrowleft_green_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property arrowright_green_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("arrowright_green_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property copy_clipboard_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("copy_clipboard_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property cut_clipboard_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("cut_clipboard_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property folder_open_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("folder_open_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property history_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("history_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property home_green_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("home_green_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property mail_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("mail_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property new_document_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("new_document_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property paste_clipboard_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("paste_clipboard_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property print_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("print_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property print_preview_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("print_preview_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property properties_doc_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("properties_doc_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property save_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("save_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property search_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("search_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property stop_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("stop_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property up_folder_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("up_folder_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property views_32_h() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("views_32_h", resourceCulture)
				Return (CType(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Class
End Namespace
